steps:  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/yasa1995/cicd-service.git']
 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}','.']

 
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']
  
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/sh
  args:
      - '-c'
      - |
        sed "s|VAR_IMAGE|gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}|g" kubernetes.yaml.tpl > kubernetes.yaml

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'kubernetes.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  
substitutions:

    _PROJECT: eastern-store-321607
    _ZONE: asia-southeast1-a
    _GKE_CLUSTER: cluster-1
    

    _DEPLOYMENTNAME: node
    _CONTAINERNAME: node    
    _REPO_NAME: apigateway
    

    _VERSION: v1.0
    
options:
    substitution_option: 'ALLOW_LOOSE'

